name: Fetch weekly drucksache

on:
  schedule:
    - cron: '0 3 * * *'  # daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Changing git settings
        run: |
          git config --global user.name 'thunderquack'
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git pull --rebase

      - name: Set up Git with new token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/thunderquack/BundestagDigest.git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run weekly fetcher
        env:
          DIP_API_KEY: ${{ secrets.DIP_API_KEY }}
        run: |
          python bundestag_down.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'thunderquack'
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git add .
          git commit -m "$(date +%F) data" || echo "No changes to commit"
          git push